server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
#      routes:
#        - id: employee-service
#          uri: lb://employee-service/
#          predicates:
#            - Path=/api/employee/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# jwt
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
