# default port for eureka server (required 8761)
server:
  port: 8761

# give a name to the eureka server
spring:
  application:
    name: eureka-server

# eureka by default will register itself as a client. So, we need to set it to false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
